automon/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from gps import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'automon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.appDefault, name='appDefault'),
    url(r'^gps/', include('gps.urls', namespace='gps')),
    url(r'^admin/', include(admin.site.urls)),
)

gps/urls.py
from django.conf.urls import patterns, include, url
from gps import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'automon.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.GpsNodesListView.as_view(), name='index'),
    url(r'^login/$', views.appLogin, name='appLogin'),
    url(r'^logout/$', views.appLogout, name='appLogout'),
    url(r'add/$', views.GpsNodeCreate.as_view(), name='add'),
    url(r'delete/(?P<pk>\d+)/$', views.GpsNodeDelete.as_view(), name='delete'),
    url(r'modify/(?P<pk>\d+)/$', views.GpsNodeUpdate.as_view(), name='modify'),
    url(r'^(?P<pk>\d+)/detail/$', views.GpsNodeDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/metricsAdd/$', views.GpsNodeMetricsAdd, name='update'),
)

gps/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone

import datetime

# Create your models here.
class GpsNode(models.Model):
    """ Define a GpsNode that collects data for a user """
    user = models.ForeignKey(User)
    ident = models.CharField(max_length=48)
    created = models.DateTimeField('Created', auto_now_add=True)
    lastActive = models.DateTimeField('LastActive', auto_now=True)

    def __unicode__(self):
        return 'GpsNode#'+self.ident

    def was_active_recently(self):
        """ check if lastActive timestamp within last 3 hour period """
        now = timezone.now()
        return now - datetime.timedelta(hours=3) <= self.lastActive 

    def get_absolute_url(self):
        return reverse('index', kwargs={'pk':self.pk})

class GpsNodeMetrics(models.Model):
    """ Define a GpsNodeMetrics attributes for metrics collected """
    node = models.ForeignKey(GpsNode)
    """ Define metrics below from node """
    vin = models.CharField(max_length=32, null=True, blank=True)
    vinCached =  models.NullBooleanField(default=None)
    latitude = models.DecimalField(max_digits=14, decimal_places=12)
    longitude = models.DecimalField(max_digits=14, decimal_places=12)
    accuracy = models.FloatField()
    speed = models.FloatField()
    altitude = models.FloatField()
    nsTimestamp = models.BigIntegerField()
    bearing = models.FloatField() 

    def __unicode__(self):
        return 'GpsNodeMetrics@'+str(self.nsTimestamp)

    def get_all_fields(self):
        """Returns a list of all field names on the instance."""
        fields = []
        for f in self._meta.fields:
            fname = f.name        
            try :
                value = getattr(self, fname)
            except User.DoesNotExist:
                value = None

            if f.name not in ('id', 'node'):
                fields.append(
                  {
                   'label':f.verbose_name, 
                   'name':f.name, 
                   'value':value,
                  }
                )
        return fields

obd/models.py
from django.db import models

# Create your models here.

gps/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, FormView
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.forms import ModelForm
from django.contrib.auth import authenticate, login, logout

from gps.models import GpsNode, GpsNodeMetrics

def appDefault(request):
    """ Root page, default landing page... if already logged in, 
         then redirect to index page, else show login page """
    if request.user.is_authenticated() and request.user.is_active:
        if request.user.is_superuser:
            print 'user %r is superuser' % request.user
            return HttpResponseRedirect('/admin')
        else:
            print 'user %r is regular' % request.user
            #return HttpResponseRedirect('gps:index')
            return HttpResponseRedirect('/gps')
    print 'Anonymous user or inactive user.. redirect to login page'
    # TODO
    #return HttpResponseRedirect(request, 'gps:login')
    return HttpResponseRedirect('/gps/login')

def appLogin(request):
   """ Handles application login """
   error_msg = ''
   if request.method == 'POST':
       myuser = request.POST['your_name']
       mypasswd = request.POST['your_passwd']
       print 'username %s, password %s' % (myuser, mypasswd)  
       user = authenticate(username=myuser, password=mypasswd)
       if user is not None:
           if user.is_active:
               print "User is valid, active"
               login(request, user)
               return HttpResponseRedirect('/gps')
           else:
               error_msg="User account disabled"
       else:
           error_msg="User/password combination is not correct"
   return render(request, 'gps/gpsnode_login.html', 
                   {'error_message' : error_msg})

def appLogout(request):
    """ Handles application logout """
    if request.method == 'POST':
       logout(request)
       return render(request, 'gps/gpsnode_login.html', {})
    return render(request, 'gps/gpsnode_confirm_logout.html', {})

class GpsNodeCreate(CreateView):
    model = GpsNode
    fields = ['ident']
    success_url = reverse_lazy('gps:index')
    template_name_suffix = '_add_form'

    def form_valid(self, form):
        # bind user into newly created node
        node = form.instance
        user = self.request.user
        print 'request user %r' % self.request.user
        if not user:
            raise Http404('Anonymous user cannot modify account. Please login and retry.')
        node.user = user
        return super(GpsNodeCreate, self).form_valid(form)

class GpsNodeUpdate(UpdateView):
    model = GpsNode
    fields = ['ident']
    success_url = reverse_lazy('gps:index')
    template_name_suffix = '_mod_form'

    def form_valid(self, form):
        # bind user into newly created node
        node = form.instance
        user = self.request.user
        print 'request user %r with pk=%r' % (user, user.id)
        if not user:
            raise Http404('Anonymous user cannot modify account. Please login and retry.')
        node.user = user
        return super(GpsNodeUpdate, self).form_valid(form)


class GpsNodeDelete(DeleteView):
    model = GpsNode
    success_url = reverse_lazy('gps:index')

    def get_object(self, queryset=None):
        obj = super(GpsNodeDelete, self).get_object(queryset)
        if not obj.user.id == self.request.user.id:
            raise Http404('Sorry..user has no permission to delete this record.')
        return obj 

class GpsNodesListView(ListView):
    model = GpsNode
    template_name = 'gps/gpsnode_list.html'
    context_object_name = 'nodes'

    def get_queryset(self):
        return GpsNode.objects.filter(user=self.request.user.id)

class GpsNodeDetailView(DetailView):
    model = GpsNode
    template_name = 'gps/gpsnode_detail.html'


class MetricsForm(ModelForm):
    class Meta:
        model = GpsNodeMetrics
        fields = ['vin', 'vinCached', 'latitude', 'longitude',
                  'accuracy', 'speed', 'altitude', 'nsTimestamp',
                  'bearing']

def GpsNodeMetricsAdd(request, pk=None):
    node = get_object_or_404(GpsNode, pk=pk)
    if request.method == 'POST':
        form = MetricsForm(request.POST)
        if form.is_valid() and node.user.id == request.user.id:
            print 'MetricsForm is valid'
            c = form.save(commit=False)
            c.node = node
            c.save()
            url = '/gps/%s/detail' % pk
            return HttpResponseRedirect(url)
        else:
            return render(request, 'gps/gpsnode_update.html',
                            {'node' : node, 'pk' : pk, 'form' : form,
                             'error_message' : 'Invalid form submitted'})
    elif node.user.id  != request.user.id:
        print 'user %r has no record for this node - %r' % (request.user, node.user)
        raise Http404('User has no such record.')
    else:
        form = MetricsForm()
        return render(request, 'gps/gpsnode_update.html', 
                        {'node' : node, 'pk' : pk, 'form' : form})

obd/views.py
from django.shortcuts import render

# Create your views here.

templates/gps/gpsnode_confirm_delete.html
{% if user.is_authenticated %}
    <p>Active User: {{ user.get_username }}. Thanks for logging in.</p>

<form action="{% url 'gps:delete' gpsnode.id %}" method="post">
  {% csrf_token %}
  {{ gpsnode }}
  <input type="submit" value="Submit"/>
</form>

{% else %}
    <p>Anonymous user, cannot perform this action.</p>
{% endif %}

templates/gps/gpsnode_confirm_logout.html
{% if user.is_authenticated %}
    <p>Hello User: {{ user.get_username }}, please confirm logout.</p>

<form action="{% url 'gps:appLogout' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Click to logout."/>
</form>

{% else %}
    <p>Anonymous user, cannot perform this action.</p>
{% endif %}

templates/gps/gpsnode_detail.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
<h1>{{ gpsnode.ident }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<a href="{% url 'gps:update' gpsnode.id %}">Add metrics...</a>

{% if gpsnode.gpsnodemetrics_set.all %}
  <table>

  <tr>
    <th> VIN </th>
    <th> VINCached </th>
    <th> Latitude </th>
    <th> Longitude </th>
    <th> Accuracy </th>
    <th> Speed </th>
    <th> Altitude </th>
    <th> Timestamp(nsecs) </th>
    <th> Bearing </th>
  </tr>

  {% for metric in gpsnode.gpsnodemetrics_set.all %}
      <tr>
      {% for f in metric.get_all_fields %}
        <td> {{ f.value | escape }} </td>
      {% endfor %}
      </tr>
  {% endfor %}
  </table>
{% else %}
  GpsNodeMetrics is empty.
{% endif %}
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

templates/gps/gpsnode_form.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
<form action="{% url 'gps:modify' gpsnode.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update"/>
</form>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

templates/gps/gpsnode_list.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
{% if nodes %}
    <table> 
        <tr>
            <th>Identifier</th>
            <th>Owner</th>
            <th>Created</th>
            <th>LastActive</th>
            <th>Recently Active?</th>
        </tr>
    {% for node in nodes %}
        <tr>
        <td><a href="{% url 'gps:detail' node.id %}">{{ node.ident }}</a></td>
        <td>{{ node.user }}</td>
        <td>{{ node.created }}</td>
        <td>{{ node.lastActive }}</td>
        <td>{{ node.was_active_recently }}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No Gps Nodes are available.</p>
{% endif %}

<a href="{% url 'gps:appLogout' %}">Logout user, {{ user.get_username }}</a>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

templates/gps/gpsnode_login.html
{% if error_message %} error_message {% endif %}
<form action='/gps/login/' method='post'>
    {% csrf_token %}
    <label for="your_name"> Login name: </label>
    <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
    <label for="your_passwd"> Login password: </label>
    <input id="your_passwd" type="password" name="your_passwd" value="{{ current_passwd }}">
    <input type="submit" value="Login">
</form>

templates/gps/gpsnode_update.html
{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>

<h1>{{ node }}</h1>

{% if error_message %} {{ error_message }} {% endif %}

<form action="{% url 'gps:update' pk %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit"/>
</form>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

templates/gps/index.html
{% if nodes %}
    <table>
        <tr>
        <th> Node </th>
        <th> Ident </th>
        <th> User </th>
        <th> Created </th>
        <th> Active recently </th>
        </tr>
    {% for node in nodes %}
        <tr> {{ node }} </tr>
        <tr> <a href="{% url 'gps:showAll' node.id %}">{{ node.ident }}</a> </tr>
        <tr> {{ node.user }} </tr>
        <tr> {{ node.created }} </tr>
        <tr> {{ node.recently_active }} </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No active Gps Nodes currently.</p>
{% endif %}

templates/gps/showAll.html
<h1>{{ node.ident }}</h1>
<!--
<ul>
{% for instance in data %}
    {% for field, value in instance.fields.items %}
        {{ field }}: {{ value }}
    {% endfor %}
{% endfor %}
</ul>
-->
<li><a href="{% url 'gps:update' id=node.id %}">Update {{ node.ident }}</a></li>

<table>
{% for m in node.gpsnodemetrics_set.all %}
    <!-- <td>{{ field }} : {{ value }}</td> -->
<tr>
    {% for info in m.get_all_fields %}
        <td> {{ info.label }} : {{ info.value }} </td>
    {% endfor %}
    <!--
    <td> {{ m.latitude }} </td>
    <td> {{ m.longitude }} </td>
    <td> {{ m.accuracy }} </td>
    <td> {{ m.speed }} </td>
    <td> {{ m.altitude }} </td>
    <td> {{ m.nsecTimestamp }} </td>
    <td> {{ m.bearing }} </td>
    <td> {{ m.vin }} </td>
    <td> {{ m.vinLastCached }} </td>
    -->
</tr>
{% endfor %}
</table>

templates/gps/update.html
<h1>{{ node.ident }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <!--
    <td> {{ m.latitude }} </td>
    <td> {{ m.longitude }} </td>
    <td> {{ m.accuracy }} </td>
    <td> {{ m.speed }} </td>
    <td> {{ m.altitude }} </td>
    <td> {{ m.nsecTimestamp }} </td>
    <td> {{ m.bearing }} </td>
    <td> {{ m.vin }} </td>
    <td> {{ m.vinLastCached }} </td>
    -->

<form action="{% url 'gps:update' id=node %}" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Submit" />
</form>